app/views/donations_mailer/thank_you_email.html.erb, spec/mailers/donations_mailer_spec.rb, spec/support/blueprints.rb
Default text for donation message.
=> [#118311055] Fixes text for donation thank email

app/models/donation.rb
Verifies environment since this endpoint doesn't work under test.
=> [#116588007, #118311055] Notifies client with link to boleto

.travis.yml, app/controllers/mobilizations/donations_controller.rb, app/models/donation.rb, app/models/form_entry.rb, db/migrate/20160603225456_add_transaction_fields_to_donations.rb, spec/controllers/mobilizations/donations_controller_spec.rb
- Encodes donations export
- Fixes permissions
=> Donations export csv

app/controllers/mobilizations/widgets_controller.rb, app/models/widget.rb, app/services/subscription_service.rb
- Fixes number of plans created according to donation widget's settings ✔︎
- Fixes method that returns or create the plans [WIP]
=> Fixes plans creation for subscriptions

Gemfile, Gemfile.lock, app/controllers/widgets/match_controller.rb, config/routes.rb, spec/controllers/widgets/match_controller_spec.rb, spec/support/blueprints.rb
- Fixes controller typo
- Added /matches/delete_where to delete all matches found with que passed params
- Added specs
=> Add match widget

app/controllers/mobilizations/form_entries_controller.rb, app/policies/mobilization_policy.rb, app/serializers/widget_serializer.rb, db/migrate/20160722185641_add_exported_at_to_widgets.rb, db/schema.rb, spec/controllers/mobilizations/form_entries_controller_spec.rb
=> Fix form entries by widget

app/controllers/activist_matches_controller.rb, app/controllers/widgets/match_controller.rb, app/models/activist_match.rb, app/models/form_entry.rb, app/models/widget.rb, app/policies/activist_match_policy.rb, app/policies/activist_policy.rb, circle.yml, config/routes.rb, db/migrate/20160804203515_create_activist_matches.rb, db/schema.rb, spec/controllers/activist_matches_controller_spec.rb, spec/controllers/widgets/match_controller_spec.rb
Demand required by https://github.com/ourcities/hub-client/issues/109
=> Create behaviour to save users data captured by Match widget.

app/models/donation.rb, app/services/subscription_sync_service.rb, db/migrate/20160807232901_add_parent_id_to_donations.rb, db/schema.rb, lib/tasks/payments.rake
- Added service to sync all new payments from a subscription to a donation
- Donation can have a parent donation
- Added rake task to run this checks periodically
=> Pagarme subscription service

app/mailers/activist_pressure_mailer.rb
=> Fix/no unsubscribe link on target's mobilization campaign

app/models/widget.rb, spec/models/widget_spec.rb
=> Correção mailchimp

app/models/widget.rb, spec/models/widget_spec.rb
=> Fix bug with mailchimp segment creation

Gemfile, Gemfile.lock, app/controllers/communities_controller.rb, app/models/activist.rb, app/models/agg_activist.rb, app/models/community.rb, app/models/form_entry.rb, config/routes.rb, db/migrate/20161222205608_add_agg_activists.rb, spec/models/activist_spec.rb
We should validate email formatting and name length
=> Add validations on activist

app/controllers/mobilizations_controller.rb, app/controllers/template_mobilizations_controller.rb, spec/controllers/mobilizations_controller_spec.rb, spec/controllers/template_mobilizations_controller_spec.rb, spec/support/blueprints.rb
Nos testes que fiz, os dados vieram na ordem correta. De qualquer forma agora as spec verificam a ordem de criação dos blocos e widgets; em código eu reforço essa particularidade.
=> Ordem de criação de widgets

app/services/donation_service.rb, app/services/subscription_service.rb, db/migrate/20170201160823_add_transaction_id_and_time_to_transaction.rb
added transaction_id
added time on payment date
=> Added more transaction data on donation reports

app/models/form_entry.rb, spec/models/form_entry_spec.rb
Correcting issue #143. Adding spec do prevent this king of error.
=> Closing issue #143

app/controllers/communities_controller.rb, app/models/activist_pressure.rb, app/models/concerns/mailchimpable.rb, app/policies/community_policy.rb
Problems resolved:
Issue #150 - Adding more information to Sentry
Issue #151  - Review the number of emails sent in each block
Issue #153 - Problem related to Pundit authorization on activist report
=> Hotfix v0.2.4 - Issues #150, #151 and #153

app/models/concerns/mailchimpable.rb
=> Issue #156 - Mailchimp does not accept email to be in uppercase in hash

Gemfile, Gemfile.lock, app/models/mobilization.rb, app/policies/mobilization_policy.rb, app/serializers/mobilization_serializer.rb, config/initializers/acts_as_taggable_on.rb, db/migrate/20170130123433_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb, db/migrate/20170130123434_add_missing_unique_indices.acts_as_taggable_on_engine.rb, db/migrate/20170130123435_add_taggings_counter_cache_to_tags.acts_as_taggable_on_engine.rb, db/migrate/20170130123436_add_missing_taggable_index.acts_as_taggable_on_engine.rb, db/migrate/20170130123437_change_collation_for_tag_names.acts_as_taggable_on_engine.rb, db/migrate/20170130123438_add_missing_indexes.acts_as_taggable_on_engine.rb, spec/controllers/mobilizations_controller_spec.rb, spec/policies/mobilization_policy_spec.rb, spec/support/blueprints.rb
Manage tags in mobilizations #171
=> Manage tags in mobilizations

app/controllers/mobilizations/donations_controller.rb, app/controllers/mobilizations/form_entries_controller.rb, app/models/donation.rb, app/models/form_entry.rb, app/services/donation_service.rb, config/locales/pt.yml, lib/tasks/activists.rake, lib/tasks/donation.rake, spec/controllers/mobilizations/form_entries_controller_spec.rb, spec/support/blueprints.rb
Issue 161 - Email and name validations on formentries
Rake tasks for updating data from pagame donations, rescue data from hashed fields and deleting unused data
=> Feature database cleaning

app/controllers/communities/activist_actions_controller.rb, app/models/activist_action.rb, app/models/community.rb, app/policies/community_policy.rb, config/routes.rb, db/migrate/20170206175947_add_customer_address_to_agg_activists.rb, db/migrate/20170208151800_create_activist_actions_view.rb
**Added address to agg_activists**
to test make a GET request in /communities/ID/agg_activists
**Added activist actions report**
to test make a GET request in /communities/ID/activist_actions
=> Add more reports

Gemfile, Gemfile.lock, app/controllers/mobilizations/donations_controller.rb, app/controllers/mobilizations/form_entries_controller.rb, app/models/donation.rb, app/models/form_entry.rb, app/services/donation_service.rb, config/locales/pt.yml, lib/tasks/activists.rake, lib/tasks/donation.rake, spec/controllers/mobilizations/form_entries_controller_spec.rb, spec/factories/factory.rb, spec/rails_helper.rb, spec/support/blueprints.rb, spec/support/factory_girl.rb
@devton já revisou antes de jogar neste branch
=> FactoryGirl + Alteração de dados de banco

app/models/activist_pressure.rb, app/models/form_entry.rb, spec/controllers/mobilizations/form_entries_controller_spec.rb, spec/models/activist_pressure_spec.rb, spec/models/form_entry_spec.rb
Problem with formentry validations
=> Hotfix validations

app/mailers/activist_pressure_mailer.rb, app/models/activist_pressure.rb
Lets send emails one by one to avoid get recipient syntax error on top of all recipients
=> should deliver one by one on pressures notifications

app/mailers/notification_mailer.rb, app/models/notification.rb, app/services/dns_service.rb, db/migrate/20170419190937_add_user_id_to_notification.rb, spec/mailers/notification_mailer_spec.rb, spec/models/notification_spec.rb
Issue #233 - Mobilizers can now be notified throw the notification system.
=> Feature notification expansion mobilizers

app/mailers/notification_mailer.rb, app/models/notification.rb, db/migrate/20170424121801_add_email_to_notification.rb, spec/factories/notifications.rb, spec/mailers/notification_mailer_spec.rb, spec/models/notification_spec.rb
Using only email to send message using the notification system
=> Issue #237 - Accepting emails to use notification system

Dockerfile, app/models/donation.rb, app/models/donation_transition.rb, app/services/donation_service.rb, app/state_machine/donation_machine.rb, db/migrate/20170519172727_only_with_transaction_id_on_donation_report.rb, db/migrate/20170525191310_add_unique_index_to_donations_transaction_id.rb, db/migrate/20170525204607_create_donation_transitions.rb, db/migrate/20170526183445_add_default_to_transaction_status.rb, db/migrate/20170529204907_add_payable_date_to_donation_reports.rb, lib/tasks/notifications.rake, spec/models/donation_spec.rb, spec/models/payable_detail_spec.rb
- Added donation state machine to better history of transaction status changes.
- Added notifications support to Donation (waiting_payment_donation, paid_donation, refused_donation)
- Added unique index to donations.transaction_id
=> Donation state machine and notifications

Gemfile, app/controllers/mobilizations/form_entries_controller.rb, app/models/activist.rb, app/models/activist_match.rb, app/models/activist_pressure.rb, app/models/concerns/tag_an_activist_omatic.rb, app/models/donation.rb, app/models/form_entry.rb, spec/controllers/mobilizations/form_entries_controller_spec.rb, spec/models/activist_spec.rb, spec/models/concerns/tag_an_activist_omatic_spec.rb, spec/models/form_entry_spec.rb, spec/requests/mobilizations/form_entries.rb
=> Issue #214 Dynamic manager automatic tags based on widget actions(donation,form_entries,pressure)

app/controllers/users_controller.rb, app/mailers/password_retriever_mailer.rb, app/views/password_retriever_mailer/retrieve.html.erb, config/locales/pt.yml, config/routes.rb, db/migrate/20170513184137_password_retrieve_into_notification_template.rb, spec/controllers/users_controller_spec.rb, spec/factories/notification_templates.rb, spec/models/notification_template_spec.rb
URI: /auth/retrieve
Method: POST
Payload: {"user": { "email": "user's email" } }
Example:
POST http://localhost:3000/auth/retrieve
{ "user": { "email": "jorge.lucas@starwars.co"} }
=> Issue 234 - Create new password for user

app/models/activist_pressure.rb, app/models/balance_operation.rb, app/models/mobilization.rb, app/models/recipient.rb, app/services/balance_operations_sync_service.rb, db/migrate/20170703190631_add_payment_average_peer_mobilization_and_community.rb, db/migrate/20170704211310_create_balance_operations.rb, lib/tasks/recipients.rake, spec/factories/balance_operations.rb, spec/models/balance_operation_spec.rb, spec/models/mobilization_spec.rb
- Added avg donations by community / mobilization functions
- Added Balance Operations table
- Added Balance Operations Sync Service, to sync balance operations from recipients
=> Feature new donation metrics

db/migrate/20170706212944_add_fetch_templates_custom_and_global.rb
- https://github.com/nossas/bonde-client/issues/692
=> Add fetch templates custom and global for graphql

db/migrate/20170718172757_add_balance_operation_summaries.rb, db/migrate/20170719173347_add_activists_to_posgraphql.rb, db/migrate/20170719175728_add_more_indexes_on_activists.rb, db/migrate/20170720191804_add_missing_grant.rb, db/migrate/20170720205244_add_community_tags.rb, db/migrate/20170721164625_fixes_on_payable_details.rb, db/migrate/20170725195744_add_mobilizations_to_activists.rb
=> [WIP] Feature more graphql

db/migrate/20170726204022_create_twilio_calls.rb, db/migrate/20170726204054_create_twilio_call_transitions.rb, db/migrate/20170726204954_add_twilio_call_actions_to_postgraphql.rb, db/migrate/20170726205318_add_twilio_call_transition_actions_to_postgraphql.rb, db/migrate/20170726205536_add_twilio_call_listen_notify_to_postgraphql.rb, db/migrate/20170726212359_grant_permissions_to_admin_on_relation_users.rb, db/migrate/20170802063458_create_twilio_configurations.rb, db/migrate/20170802070642_add_create_twilio_configuration_action_to_postgraphql.rb, db/migrate/20170802071256_add_update_twilio_configuration_action_to_postgraphql.rb
- Create tables to store the phone pressures #340
- Create tables to store the BONDE's communities twilio configurations #350
- Feature phone pressure nossas/bonde-client#764
=> Feature twilio calls close #350

app/policies/widget_policy.rb, db/migrate/20170726204022_create_twilio_calls.rb, db/migrate/20170726204054_create_twilio_call_transitions.rb, db/migrate/20170726204954_add_twilio_call_actions_to_postgraphql.rb, db/migrate/20170726205318_add_twilio_call_transition_actions_to_postgraphql.rb, db/migrate/20170726205536_add_twilio_call_listen_notify_to_postgraphql.rb, db/migrate/20170726212359_grant_permissions_to_admin_on_relation_users.rb, db/migrate/20170802063458_create_twilio_configurations.rb, db/migrate/20170802070642_add_create_twilio_configuration_action_to_postgraphql.rb, db/migrate/20170802071256_add_update_twilio_configuration_action_to_postgraphql.rb, spec/policies/widget_policy_spec.rb
https://github.com/nossas/bonde-client/issues/791
=> Enable option to disable edit field on pressure widget

db/migrate/20170810125626_chage_context_community_on_custom_templates.rb
Issues
- Error when try to filter my templates. Closes #354
=> Hotfix custom templates

db/migrate/20170814184009_add_facebook_bot_interaction_manipulation_views_to_postgraphql.rb, db/migrate/20170815175734_change_facebook_bot_recipients_table_view_to_postgraphql.rb
- Add views to ease the manipulation of bot interactions #360
=> Feature facebook bot handle interactions

db/migrate/20170906143724_create_facebook_bot_activists.rb, db/migrate/20170913182113_save_facebook_bot_activists_data.rb, db/migrate/20170913212556_add_facebook_bot_activists_search_actions_to_postgraphql.rb
- Facebook bot mass message nossas/bonde-client#829
=> Feature facebook bot activists segmentation

app/models/community.rb, config/schedule.rb, db/migrate/20171009181239_add_total_sum_transfer_operations_from_community.rb
- Added balance sum function
- Fixes invitation to look for already created with same code
=> Feature balance operations sum

app/controllers/communities_controller.rb, app/controllers/mobilizations/blocks_controller.rb, app/controllers/mobilizations/widgets_controller.rb, app/controllers/mobilizations_controller.rb, app/controllers/widgets_controller.rb, app/models/block.rb, app/models/community.rb, app/models/mobilization.rb, app/models/widget.rb, app/policies/community_policy.rb, app/serializers/block_serializer.rb, app/workers/community_mailchimp_resync_worker.rb, config/routes.rb, db/migrate/20171030165448_add_deleted_at_to_some_tables.rb, db/migrate/20171106183342_add_profile_data_to_community_activist.rb, spec/controllers/communities_controller_spec.rb, spec/controllers/mobilizations/blocks_controller_spec.rb, spec/models/block_spec.rb, spec/models/community_spec.rb, spec/models/mobilization_spec.rb, spec/models/widget_spec.rb
- add resync with mailchimp
- add deleted_at fields
=> Add activist resync with mailchimp

app/services/balance_operations_sync_service.rb, lib/tasks/recipients.rake
@lpirola @devton ficou com 3 tasks agora (uma para cada status)
Waiting Payment => sync_waiting_payment_balance_operations
Available => sync_availables_balance_operations
Transferred => sync_transferred_balance_operations
=> Feature task balance operations with status

db/migrate/20180405184423_add_community_id_to_twilio_calls.rb, db/migrate/20180405192442_change_add_twilio_call_function_with_community_id.rb, db/migrate/20180411122937_add_twilio_configuration_notification_trigger.rb
- [[#156110820]](https://www.pivotaltracker.com/story/show/156110820) As campaigner, I want to configure the twilio account at my community so that I can use the pressure widget via phone connected to that specific twilio account
=> Feature workflow with community context

db/migrate/20180124225505_add_micro_services_schema.rb
=> fix migrations create a microservices role when exists #469

db/migrate/20180607172013_adds_function_to_get_trending_mobs.rb, db/migrate/20180611201937_change_all_mobilizations_v2.rb, db/migrate/20180611204413_create_user_communities_to_v2.rb, db/migrate/20180611204747_change_view_communities_to_public_access_in_v2.rb, db/migrate/20180611205332_create_trending_mobs_v2.rb, db/migrate/20180611205937_add_communities_data_to_mobilization.rb, spec/sql-specs/postgraphql/function.mobilizations_test.sql
Um exemplo para executar essa mutation 
```
mutation {
mobilizations(input: {
days: 90
}) {
json
}
}
```
- criação de uma mutation para listar as moblizações com score e possiblidade de filtragem por dias. (2 dias, 90 dias) por exemplo
=> Trending Mobs v2

app/policies/widget_policy.rb, db/migrate/20181113143400_add_external_resource_on_donation_stats.rb, spec/policies/widget_policy_spec.rb
Calc donation stats with external resource donation.
=> Feature external resource donation

lib/tasks/notifications.rake
- https://github.com/nossas/bonde-client/issues/1283
=> feat: add invite template

app/models/activist_pressure.rb
This reverts commit 0f286de01a84f075e93e0813d3f83db145140b03.
=> Revert "fix: disable send pressure-mail"
